# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/poa',
                'doc_host': 'https://zqshan.github.io',
                'git_url': 'https://github.com/zqshan/poa',
                'lib_path': 'poa'},
  'syms': {'poa.core': {'poa.core.foo': ('core.html#foo', 'poa/core.py')}}}
